/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#ddb8ff",
        "secondary": "#adc6ff",
        "primary-fixed": "#f0dbff",
        "primary": "#ddb8ff",
        "inverse-surface": "#e5e2e1",
        "surface-variant": "#353534",
        "on-secondary-fixed": "#001a42",
        "outline": "#988ca0",
        "on-secondary-container": "#e6ecff",
        "surface-bright": "#3a3939",
        "on-error": "#690005",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed": "#2c0051",
        "surface-container": "#201f1f",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#cfc2d7",
        "tertiary": "#ffb0cd",
        "primary-container": "#9333ea",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#004395",
        "secondary-container": "#0566d9",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#8c0053",
        "on-primary-container": "#f6e6ff",
        "on-primary-fixed-variant": "#6800b4",
        "error": "#ffb4ab",
        "surface-dim": "#131313",
        "tertiary-fixed": "#ffd9e4",
        "surface-container-highest": "#353534",
        "surface-container-low": "#1c1b1b",
        "outline-variant": "#4d4354",
        "inverse-on-surface": "#313030",
        "secondary-fixed-dim": "#adc6ff",
        "background": "#131313",
        "tertiary-container": "#c4257a",
        "surface-container-high": "#2a2a2a",
        "on-primary": "#490080",
        "on-background": "#e5e2e1",
        "inverse-primary": "#861fdd",
        "primary-fixed-dim": "#ddb8ff",
        "on-tertiary-container": "#ffe5ec",
        "tertiary-fixed-dim": "#ffb0cd",
        "on-secondary": "#002e6a",
        "surface": "#131313",
        "secondary-fixed": "#d8e2ff",
        "on-tertiary-fixed": "#3e0022",
        "on-tertiary": "#640039"
      },
      spacing: {
        "gutter-mobile": "16px",
        "margin-desktop": "64px",
        "container-max-width": "1200px",
        "gutter-desktop": "24px",
        "margin-mobile": "20px",
        "unit": "4px"
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
      }
    },
  },
  plugins: [],
}
